# -*- coding: utf-8 -*-
"""AI_Text_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldyES3cHqCkEsa7ynJtxOGZSkBOTI0Jq
"""

"""
AI Text Analyzer using Groq

This script:
1. Reads an article from a text file
2. Sends it to a Groq LLM
3. Extracts:
   - Summary
   - Sentiment
   - Key topics

Author: Mohammed Anas Khan
"""

import os
import json
from groq import Groq
from dotenv import load_dotenv


# Load environment variables from .env
load_dotenv()

# Initialize Groq client
client = Groq(api_key=("GROQ_API_KEY"))


# -----------------------------
# Step 1: Read the article
# -----------------------------
with open("article.txt", "r") as file:
    text = file.read()


# -----------------------------
# Step 2: Create prompt
# -----------------------------
prompt = f"""
Analyze this text and return JSON only.
No extra text, just JSON.

Analyze this text:
{text}

Return exactly this format:
{{
    "summary": "...",
    "sentiment": "positive or negative or neutral",
    "topics": ["topic1", "topic2", "topic3"]
}}
"""


# -----------------------------
# Step 3: Send request to Groq
# -----------------------------
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {
            "role": "system",
            "content": "You are a text analyzer. Always reply in JSON only."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]
)


# Get model response
results = response.choices[0].message.content
print("Raw model response:")
print(results)


# -----------------------------
# Step 4: Parse JSON safely
# -----------------------------
try:
    data = json.loads(results)

    print("\n📊 Analysis Result")
    print("-------------------")
    print(f"Summary   : {data['summary']}")
    print(f"Sentiment : {data['sentiment']}")
    print(f"Topics    : {data['topics']}")

except json.JSONDecodeError:
    print("\n⚠️ Could not parse JSON")
    print(results)



